[package]
name = "hecto"
version = "0.1.0"
edition = "2021"
authors = ["lnkkerst <lnkkerst04@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25"
